### ISSUE TITLE
[Bug]: Slimes with TargetAttacker ai crash the game on spawn

### ISSUE THREAD

**Issue by MathiusXII** [p1ut0nium-git/Rough-Mobs-Revamped#78]
### What happened?

Game crashes when the slime with TargetAttacker ai spawns. (Any type of slime, not just vanilla)

### Minecraft Version

1.12.2 (Edge)

### Forge Version

1.12.2-14.23.5.2860

### Mod (RMR) Version

1.12.2-2.3.23

### Crash Log

```shell
Description: Exception ticking world

java.lang.ClassCastException: com.mic.betterslimes.entity.slimes.BlackSlime cannot be cast to net.minecraft.entity.EntityCreature
    at com.p1ut0nium.roughmobsrevamped.misc.TargetHelper.setTargets(TargetHelper.java:122)
    at com.p1ut0nium.roughmobsrevamped.RoughApplier.onEntitySpawn(RoughApplier.java:231)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4029_RoughApplier_onEntitySpawn_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.world.World.spawnEntity(World.java:1209)
    at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:1058)
    at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:160)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:203)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:750)
```

**Comment by MathiusXII** [comment]
Didn't this happen on Rough Mobs 2?
