### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SenZ01** [p1ut0nium-git/Rough-Mobs-Revamped#84]
### What happened?

I started porting my 1.12 Modpack to 1.16, decided to put in Rough Mobs Revamped and spend 2 Hours figuring out the cause for the crash and found out that RMR is the cause.

at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:178) ~[?:?] {re:classloading}
at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:classloading}
at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:classloading}

Client Crashed upon entering the world and starts fine without RMR.

### Minecraft Version

1.16.5 (Default)

### Forge Version

1.16.5-36.2.34

### Mod (RMR) Version

1.16.5-0.0.3

### Crash Log

```shell
https://pastes.dev/SaXuTedy1Q
```

**Comment by FelixRobotics** [comment]
same deal here, time to check out improved mobs in the mean time
